# Generated by Django 3.1.7 on 2021-04-08 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MeetingDate', models.DateField()),
                ('MeetingTime', models.TimeField()),
                ('MeetingLocation', models.TextField()),
                ('Agenda', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Meeting',
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResourceName', models.CharField(max_length=255)),
                ('ResourceType', models.CharField(max_length=255)),
                ('ResourceURL', models.URLField()),
                ('ResourceDate', models.DateField()),
                ('ResourceDescription', models.TextField(blank=True, null=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Resources',
            },
        ),
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MinuetesText', models.TextField(blank=True, null=True)),
                ('Attendance', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('MeetingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Club.meeting')),
            ],
            options={
                'db_table': 'Minutes',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventTitle', models.CharField(max_length=255)),
                ('EventLocation', models.CharField(max_length=255)),
                ('EventDate', models.DateField()),
                ('EventTime', models.TimeField()),
                ('EventDescription', models.TextField(blank=True, null=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Event',
            },
        ),
    ]
