# Generated by Django 3.1.7 on 2021-05-28 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0002_meeting_meetingtitle'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meetingminutes',
            table='Meeting Minutes',
        ),
    ]
