# Generated by Django 3.1.7 on 2021-05-28 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0003_auto_20210527_1722'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meetingminutes',
            table='Minutes',
        ),
    ]
