# Generated by Django 3.1.7 on 2021-05-28 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0004_auto_20210527_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingminutes',
            name='Attendance',
        ),
    ]
