# Generated by Django 3.1.7 on 2021-05-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0005_remove_meetingminutes_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='Attendance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
