# Generated by Django 3.1.7 on 2021-05-28 02:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0007_auto_20210527_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingminutes',
            name='Attendance',
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='Attendance',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
