# Generated by Django 3.1.7 on 2021-05-28 03:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Club', '0010_remove_meetingminutes_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='Attendance',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='meetingminutes',
            table='MeetingMinutes',
        ),
    ]
