# Generated by Django 3.1.7 on 2021-05-28 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0013_auto_20210527_2153'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meetingminutes',
            table='Minutes',
        ),
    ]
