# Generated by Django 3.1.7 on 2021-05-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0018_auto_20210527_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingminutes',
            name='Attendance',
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='Attendance',
            field=models.CharField(default='yes', max_length=255),
            preserve_default=False,
        ),
    ]
